/*
 * Copyright (c) 2018-present, easy-4-java (https://github.com/easy-4-java).
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.ishumei.spring.boot.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

import lombok.Data;

/**
 * Standard response envelope returned by the synchronous text
 * anti-fraud endpoint.
 *
 * <p>In addition to the field accessors generated by Lombok's
 * {@link Data}, this class provides three convenience predicates
 * that summarise the risk decision:</p>
 * <ul>
 *     <li>{@link #isSuccess()} &mdash; the call completed without a
 *     timeout and the platform returned code {@code 1100}.</li>
 *     <li>{@link #isPass()} / {@link #isReview()} / {@link #isReject()}
 *     &mdash; the call was successful <em>and</em> the risk level
 *     matches the corresponding label.</li>
 * </ul>
 *
 * <p>The {@code detail} property is serialised as a JSON string so
 * the SDK remains agnostic of the evolving detail schema; callers
 * that need to inspect details should re-parse the string with
 * Jackson.</p>
 *
 * @author [@Loong Wan](https://github.com/loong10k)
 * @since 3.0.0
 * @see AntiFraudImageResponse
 * @see AntiFraudVideoResponse
 * @see AntiFraudRequest
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
@Data
public class AntiFraudResponse {

	/**
	 * Platform response code. The value {@code 1100} denotes success;
	 * any other code indicates an error (full list at
	 * <a href="https://www.ishumei.com/help/documents.html?id=24000">
	 * Ishumei docs</a>).
	 */
	@JsonProperty("code")
	private String code;

	/**
	 * Human-readable description of the response code.
	 */
	@JsonProperty("message")
	private String message;

	/**
	 * Globally unique identifier of the request. Useful for tracing a
	 * decision back to the platform logs.
	 */
	@JsonProperty("requestId")
	private String requestId;

	/**
	 * Numeric risk score in the range {@code [0, 1000]}. Higher values
	 * indicate greater risk.
	 */
	@JsonProperty("score")
	private int score;

	/**
	 * Coarse-grained risk verdict. Possible values are
	 * <ul>
	 *     <li>{@code PASS} &mdash; normal content, allow,</li>
	 *     <li>{@code REVIEW} &mdash; suspicious, manual review,</li>
	 *     <li>{@code REJECT} &mdash; violation, block.</li>
	 * </ul>
	 */
	@JsonProperty("riskLevel")
	private String riskLevel;

	/**
	 * Server-side timeout flag. {@code 0} denotes a normal response,
	 * {@code 501} indicates the platform timed out while computing the
	 * score.
	 */
	@JsonProperty("status")
	private int status;

	/**
	 * Risk-detail object serialised as a JSON string. The schema is
	 * intentionally opaque; deserialize it with Jackson if you need to
	 * inspect individual hits.
	 */
	@JsonProperty("detail")
	private String detail;

	/**
	 * Reports whether the call succeeded without a timeout and the
	 * platform returned the canonical success code {@code 1100}.
	 *
	 * @return {@code true} when {@link #status} is {@code 0} and
	 *         {@link #code} equals {@code "1100"}.
	 */
	public boolean isSuccess() {
		return status == 0 && code.equals("1100");
	}

	/**
	 * Reports whether the response indicates the content is normal
	 * and should be allowed through.
	 *
	 * @return {@code true} when {@link #isSuccess()} returns
	 *         {@code true} and {@link #riskLevel} equals
	 *         {@code "PASS"}.
	 */
	public boolean isPass() {
		return isSuccess() && riskLevel.equals("PASS");
	}

	/**
	 * Reports whether the response indicates the content is
	 * suspicious and should be reviewed manually.
	 *
	 * @return {@code true} when {@link #isSuccess()} returns
	 *         {@code true} and {@link #riskLevel} equals
	 *         {@code "REVIEW"}.
	 */
	public boolean isReview() {
		return isSuccess() && riskLevel.equals("REVIEW");
	}

	/**
	 * Reports whether the response indicates the content is a
	 * violation and should be blocked immediately.
	 *
	 * @return {@code true} when {@link #isSuccess()} returns
	 *         {@code true} and {@link #riskLevel} equals
	 *         {@code "REJECT"}.
	 */
	public boolean isReject() {
		return isSuccess() && riskLevel.equals("REJECT");
	}

}